// create article
export const CREATE_ARTICLE_ATTEMPT = "CREATE_ARTICLE_ATTEMPT";
export const CREATE_ARTICLE_SUCCESS = "CREATE_ARTICLE_SUCCESS";
export const CREATE_ARTICLE_ERROR = "CREACTE_ARTICLE_ERROR";
// delete article
export const DELETE_ARTICLE_ATTEMPT = "DELETE_ARTICLE_ATTEMPT";
export const DELETE_ARTILCE_SUCCESS = "DELETE_ARTILCE_SUCCESS";
export const DELETE_ARTILCE_ERROR = "DELETE_ARTILCE_ERROR";
// get all articles
export const GET_ALL_ARTICLES_ATTEMPT = "GET_ALL_ARTICLES_ATTEMPT";
export const GET_ALL_ARTICLES_SUCCESS = "GET_ALL_ARTICLES_SUCCESS";
// get article by category
export const GET_ARTICLE_BY_CATEGORY_ATTEMPT = "GET_ARTICLE_BY_CATEGORY_ATTEMPT";
export const GET_ARTICLE_BY_CATEGORY_SUCCESS = "GET_ARTICLE_BY_CATEGORY_SUCCESS";
export const GET_ARTICLE_BY_CATEGORY_ERROR = "GET_ARTICLE_BY_CATEGORY_ERROR";
// get article
export const GET_ARTICLE_ATTEMPT = "GET_ARTICLE_ATTEMPT";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_ERROR = "GET_ARTICLE_ERROR";
// get category list (breadcrumbs)
// export const GET_ARTICLE_CATEGORY_LIST_ATTEMPT = "GET_ARTICLE_CATEGORY_LIST_ATTEMPT";
// export const GET_ARTICLE_CATEGORY_LIST_SUCCESS = "GET_ARTICLE_CATEGORY_LIST_SUCCESS";
// export const GET_ARTICLE_CATEGORY_LIST_ERROR = "GET_ARTICLE_CATEGORY_LIST_ERROR";
// update article
export const UPDATE_ARTICLE_ATTEMPT = "UPDATE_ARTICLE_ATTEMPT";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_ERROR = "UPDATE_ARTICLE_ERROR";
