// create category
export const CREATE_CATEGORY_ATTEMPT = "CREATE_CATEGORY_ATTEMPT";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_ERROR = "CREATE_CATEGORY_SUCCESS";
// delete category
export const DELETE_CATEGORY_ATTEMPT = "DELETE_CATEGORY_ATTEMPT";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_ERROR = "DELETE_CATEGORY_ERROR";
// get all category
export const GET_ALL_CATEGORY_ATTEMPT = "GET_ALL_CATEGORY_ATTEMPT";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
// get category by id
export const GET_CATEGORY_LIST_ATTEMPT = "GET_CATEGORY_LIST_ATTEMPT";
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS";
export const GET_CATEGORY_LIST_ERROR = "GET_CATEGORY_LIST_ERROR";
// update category
export const UPDATE_CATEGORY_ATTEMPT = "UPDATE_CATEGORY_ATTEMPT";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";
