// create recipe
export const CREATE_RECIPE_ATTEMPT = "CREATE_RECIPE_ATTEMPT";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const CREATE_RECIPE_ERROR = "CREACTE_RECIPE_ERROR";
// delete recipe
export const DELETE_RECIPE_ATTEMPT = "DELETE_RECIPE_ATTEMPT";
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS";
export const DELETE_RECIPE_ERROR = "DELETE_RECIPE_ERROR";
// get all recipe
export const GET_ALL_RECIPE_ATTEMPT = "GET_ALL_RECIPE_ATTEMPT";
export const GET_ALL_RECIPE_SUCCESS = "GET_ALL_RECIPE_SUCCESS";
// get recipe by category
export const GET_RECIPE_BY_CATEGORY_ATTEMPT = "GET_RECIPE_BY_CATEGORY_ATTEMPT";
export const GET_RECIPE_BY_CATEGORY_SUCCESS = "GET_RECIPE_BY_CATEGORY";
export const GET_RECIPE_BY_CATEGORY_ERROR = "GET_RECIPE_BY_CATEGORY_ERROR";
// get recipe
export const GET_RECIPE_ATTEMPT = "GET_RECIPE_ATTEMPT";
export const GET_RECIPE_SUCCESS = "GET_RECIPE_SUCCESS";
export const GET_RECIPE_ERROR = "GET_RECIPE_ERROR";
// get category list (breadcrumbs)
// export const GET_RECIPE_CATEGORY_LIST_ATTEMPT = "GET_RECIPE_CATEGORY_LIST_ATTEMPT";
// export const GET_RECIPE_CATEGORY_LIST_SUCCESS = "GET_RECIPE_CATEGORY_LIST_SUCCESS";
// export const GET_RECIPE_CATEGORY_LIST_ERROR = "GET_RECIPE_CATEGORY_LIST_ERROR";
// update recipe
export const UPDATE_RECIPE_ATTEMPT = "UPDATE_RECIPE_ATTEMPT";
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
export const UPDATE_RECIPE_ERROR = "UPDATE_RECIPE_ERROR";
